"use client";

import Link from "next/link";
import { useAuth } from "@/context/AuthContext";
import { CalendarDays, Heart, Mail, MessageSquareText, UserRound, ArrowRight } from "lucide-react";

export default function ProfilePage() {
  const { user, isAuthenticated } = useAuth();
  if (!isAuthenticated) return <main className="min-h-screen bg-[#faf8f6] py-24 text-center"><UserRound className="mx-auto text-[#9b8171]" /><h1 className="mt-4 text-3xl font-semibold">Your account</h1><Link href="/login" className="mt-6 inline-flex rounded-xl bg-[#30251f] px-5 py-3 text-sm font-semibold text-white">Sign in</Link></main>;
  return <main className="min-h-screen bg-[#faf8f6]"><div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#9b8171]">Account</p><h1 className="mt-2 text-4xl font-semibold text-[#30251f]">Welcome, {user?.fullName}</h1><div className="mt-7 rounded-3xl border border-[#eee5df] bg-white p-7 shadow-sm"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#30251f] text-xl font-semibold text-white">{user?.fullName?.charAt(0).toUpperCase()}</div><div><h2 className="text-xl font-semibold">{user?.fullName}</h2><p className="mt-1 flex items-center gap-2 text-sm text-[#81746d]"><Mail size={14} />{user?.email}</p></div></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Link href="/roadmap" className="group rounded-2xl border border-[#eee5df] bg-white p-6 shadow-sm hover:shadow-md"><CalendarDays className="text-[#9b8171]" /><h3 className="mt-5 font-semibold">Wedding roadmap</h3><p className="mt-1 text-sm text-[#81746d]">Manage your date, categories and vendors.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#8e685e]">Open roadmap <ArrowRight size={14} /></span></Link><Link href="/reviews" className="group rounded-2xl border border-[#eee5df] bg-white p-6 shadow-sm hover:shadow-md"><MessageSquareText className="text-[#9b8171]" /><h3 className="mt-5 font-semibold">My reviews</h3><p className="mt-1 text-sm text-[#81746d]">See the reviews you've written and their status.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#8e685e]">View reviews <ArrowRight size={14} /></span></Link><Link href="/favorites" className="group rounded-2xl border border-[#eee5df] bg-white p-6 shadow-sm hover:shadow-md"><Heart className="text-[#9b8171]" /><h3 className="mt-5 font-semibold">Saved favorites</h3><p className="mt-1 text-sm text-[#81746d]">Review the vendors and services you saved.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#8e685e]">View favorites <ArrowRight size={14} /></span></Link></div></div></main>
}
