"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { Search, Sparkles, Store, Volume2, VolumeX } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";
import { media } from "@/lib/media";

const HERO_VIDEO_URL = media(
  "https://res.cloudinary.com/dqwoefi7l/video/upload/v1790028198/JEKA_zowofv.mp4",
);

// First frame of the hero video, generated by Cloudinary (shown until the
// video starts, and for visitors with data-saver / reduced motion).
const HERO_POSTER_URL = media(
  "https://res.cloudinary.com/dqwoefi7l/video/upload/so_2,w_1600,q_auto,f_auto/v1790028198/JEKA_zowofv.jpg",
);

/** Full-height video hero with the main headline and CTAs. */
export function HomeHero() {
  const { t } = useLanguage();
  const videoRef = useRef<HTMLVideoElement>(null);
  const [isMuted, setIsMuted] = useState(true);

  const toggleMute = () => {
    if (videoRef.current) {
      videoRef.current.muted = !videoRef.current.muted;
      setIsMuted(videoRef.current.muted);
    }
  };

  return (
    <section className="relative flex min-h-[calc(100vh-4.5rem)] items-center justify-center overflow-hidden">
      <div className="absolute inset-0 z-0">
        <div className="absolute inset-0 z-10 bg-linear-to-b from-[#1c140f]/70 via-[#1c140f]/55 to-[#1c140f]/75 sm:bg-[#1c140f]/55" />

        <video
          ref={videoRef}
          autoPlay
          loop
          muted={isMuted}
          playsInline
          preload="metadata"
          poster={HERO_POSTER_URL}
          className="h-full w-full object-cover object-[center_35%] sm:scale-105 sm:object-center"
        >
          <source src={HERO_VIDEO_URL} type="video/mp4" />
        </video>
      </div>

      <button
        type="button"
        onClick={toggleMute}
        aria-label={t("home.hero.toggleSound")}
        className="absolute end-5 top-5 z-30 flex h-11 w-11 items-center justify-center rounded-full border border-white/20 bg-black/40 text-white backdrop-blur-sm transition hover:bg-black/60 sm:end-8 sm:top-8"
      >
        {isMuted ? <VolumeX size={18} /> : <Volume2 size={18} />}
      </button>

      <div className="relative z-20 mx-auto w-full px-4 py-16 text-center sm:px-6 lg:max-w-10/12 lg:px-8">
        <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-1.5 backdrop-blur">
          <Sparkles className="h-3.5 w-3.5 text-[#e8cd9a]" />

          <span className="text-[10px] font-medium uppercase tracking-[0.4em] text-white/80">
            5digea
          </span>
        </div>

        <h1 className="font-serif text-4xl font-light leading-tight rtl:leading-snug text-white drop-shadow-sm sm:text-5xl lg:text-6xl">
          {t("home.hero.title")}{" "}
          <span className="italic rtl:not-italic text-[#e8cd9a]">
            {t("home.hero.titleHighlight")}
          </span>
        </h1>

        <p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/80 sm:text-base">
          {t("home.hero.description")}
        </p>

        <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row">
          <Link
            href="/services"
            className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-3.5 text-sm font-medium text-[#30251f] shadow-lg transition hover:bg-[#f3ede6] hover:shadow-xl"
          >
            <Search size={16} />
            {t("home.hero.exploreServices")}
          </Link>

          <Link
            href="/vendors"
            className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 bg-white/10 px-7 py-3.5 text-sm font-medium text-white backdrop-blur transition hover:bg-white/20"
          >
            <Store size={16} />
            {t("home.hero.browseVendors")}
          </Link>
        </div>

        <div className="mt-14 flex justify-center">
          <div className="flex h-9 w-5.5 items-start justify-center rounded-full border-2 border-white/40 pt-1.5">
            <div className="h-1.5 w-1 animate-bounce rounded-full bg-white/70" />
          </div>
        </div>
      </div>
    </section>
  );
}
